package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysFunction<M extends BaseSysFunction<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * �˵�����
	 */
	public void setFunctionname(java.lang.String functionname) {
		set("functionname", functionname);
	}
	
	/**
	 * �˵�����
	 */
	public java.lang.String getFunctionname() {
		return getStr("functionname");
	}

	/**
	 * �˵�����
	 */
	public void setFunctioncode(java.lang.String functioncode) {
		set("functioncode", functioncode);
	}
	
	/**
	 * �˵�����
	 */
	public java.lang.String getFunctioncode() {
		return getStr("functioncode");
	}

	/**
	 * ��ID
	 */
	public void setPid(java.lang.String pid) {
		set("pid", pid);
	}
	
	/**
	 * ��ID
	 */
	public java.lang.String getPid() {
		return getStr("pid");
	}

	/**
	 * ·��
	 */
	public void setUrl(java.lang.String url) {
		set("url", url);
	}
	
	/**
	 * ·��
	 */
	public java.lang.String getUrl() {
		return getStr("url");
	}

	/**
	 * L-���ӣ�M-�˵���B-��ť��A-�ӿ�
	 */
	public void setFunctiontype(java.lang.String functiontype) {
		set("functiontype", functiontype);
	}
	
	/**
	 * L-���ӣ�M-�˵���B-��ť��A-�ӿ�
	 */
	public java.lang.String getFunctiontype() {
		return getStr("functiontype");
	}

	/**
	 * �˵�˳��
	 */
	public void setFunctionsort(java.lang.String functionsort) {
		set("functionsort", functionsort);
	}
	
	/**
	 * �˵�˳��
	 */
	public java.lang.String getFunctionsort() {
		return getStr("functionsort");
	}

	/**
	 * ����ͼ��
	 */
	public void setIconurl(java.lang.String iconurl) {
		set("iconurl", iconurl);
	}
	
	/**
	 * ����ͼ��
	 */
	public java.lang.String getIconurl() {
		return getStr("iconurl");
	}

	/**
	 * �Ƿ����� 0-���� 1-����
	 */
	public void setIsenable(java.lang.String isenable) {
		set("isenable", isenable);
	}
	
	/**
	 * �Ƿ����� 0-���� 1-����
	 */
	public java.lang.String getIsenable() {
		return getStr("isenable");
	}

	/**
	 * ������
	 */
	public void setCreateuser(java.lang.String createuser) {
		set("createuser", createuser);
	}
	
	/**
	 * ������
	 */
	public java.lang.String getCreateuser() {
		return getStr("createuser");
	}

	/**
	 * ������ID
	 */
	public void setCreateid(java.lang.String createid) {
		set("createid", createid);
	}
	
	/**
	 * ������ID
	 */
	public java.lang.String getCreateid() {
		return getStr("createid");
	}

	/**
	 * ����ʱ��
	 */
	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * ����ʱ��
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	/**
	 * �޸���
	 */
	public void setUpdateuser(java.lang.String updateuser) {
		set("updateuser", updateuser);
	}
	
	/**
	 * �޸���
	 */
	public java.lang.String getUpdateuser() {
		return getStr("updateuser");
	}

	/**
	 * �޸���ID
	 */
	public void setUpdateid(java.lang.String updateid) {
		set("updateid", updateid);
	}
	
	/**
	 * �޸���ID
	 */
	public java.lang.String getUpdateid() {
		return getStr("updateid");
	}

	/**
	 * �޸�ʱ��
	 */
	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * �޸�ʱ��
	 */
	public java.lang.String getUpdatetime() {
		return getStr("updatetime");
	}

}
