package com.baomidou.kisso.dao;

import com.baomidou.kisso.dao.base.BaseExamUserOrg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ExamUserOrg extends BaseExamUserOrg<ExamUserOrg> {
	
}
