package com.baomidou.kisso.dao;

import com.baomidou.kisso.dao.base.BaseLoginLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoginLog extends BaseLoginLog<LoginLog> {
	
}
