package com.baomidou.kisso.dao;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("escort_site", "id", EscortSite.class);
		arp.addMapping("exam_user_org", "id", ExamUserOrg.class);
		arp.addMapping("login_log", "id", LoginLog.class);
		arp.addMapping("sys_function", "id", SysFunction.class);
		arp.addMapping("sys_log", "id", SysLog.class);
		arp.addMapping("sys_role", "id", SysRole.class);
		arp.addMapping("sys_role_function", "id", SysRoleFunction.class);
		arp.addMapping("sys_user", "id", SysUser.class);
	}
}

