package com.baomidou.kisso.dao;

import com.baomidou.kisso.dao.base.BaseEscortSite;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class EscortSite extends BaseEscortSite<EscortSite> {
	
}
