package com.baomidou.kisso.dao;

import com.baomidou.kisso.dao.base.BaseSysFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysFunction extends BaseSysFunction<SysFunction> {
	
}
