package com.baomidou.kisso.dao;

import com.baomidou.kisso.dao.base.BaseSysRoleFunction;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysRoleFunction extends BaseSysRoleFunction<SysRoleFunction> {
	
}
