package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRoleFunction<M extends BaseSysRoleFunction<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * �˵�ID
	 */
	public void setFunctionid(java.lang.String functionid) {
		set("functionid", functionid);
	}
	
	/**
	 * �˵�ID
	 */
	public java.lang.String getFunctionid() {
		return getStr("functionid");
	}

	/**
	 * ��ɫID
	 */
	public void setRoleid(java.lang.String roleid) {
		set("roleid", roleid);
	}
	
	/**
	 * ��ɫID
	 */
	public java.lang.String getRoleid() {
		return getStr("roleid");
	}

}
