package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEscortSite<M extends BaseEscortSite<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * 流转点名称
	 */
	public void setEsname(java.lang.String esname) {
		set("esname", esname);
	}
	
	/**
	 * 流转点名称
	 */
	public java.lang.String getEsname() {
		return getStr("esname");
	}

	/**
	 * 流转点地址
	 */
	public void setEsaddress(java.lang.String esaddress) {
		set("esaddress", esaddress);
	}
	
	/**
	 * 流转点地址
	 */
	public java.lang.String getEsaddress() {
		return getStr("esaddress");
	}

	/**
	 * 所属机构名称
	 */
	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	/**
	 * 所属机构名称
	 */
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}

	/**
	 * 所属机构编码
	 */
	public void setOrgcode(java.lang.String orgcode) {
		set("orgcode", orgcode);
	}
	
	/**
	 * 所属机构编码
	 */
	public java.lang.String getOrgcode() {
		return getStr("orgcode");
	}

	/**
	 * 经度
	 */
	public void setLng(java.lang.String lng) {
		set("lng", lng);
	}
	
	/**
	 * 经度
	 */
	public java.lang.String getLng() {
		return getStr("lng");
	}

	/**
	 * 纬度
	 */
	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}
	
	/**
	 * 纬度
	 */
	public java.lang.String getLat() {
		return getStr("lat");
	}

	/**
	 * 值班电话
	 */
	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	/**
	 * 值班电话
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	/**
	 * treecode
	 */
	public void setTreecode(java.lang.String treecode) {
		set("treecode", treecode);
	}
	
	/**
	 * treecode
	 */
	public java.lang.String getTreecode() {
		return getStr("treecode");
	}

	/**
	 * 备注
	 */
	public void setBak(java.lang.String bak) {
		set("bak", bak);
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getBak() {
		return getStr("bak");
	}

}
