package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLoginLog<M extends BaseLoginLog<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * �û�id
	 */
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	/**
	 * �û�id
	 */
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	/**
	 * �û���/�˺�
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * �û���/�˺�
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * �û���ʵ����/�û���
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	/**
	 * �û���ʵ����/�û���
	 */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * ip��ַ
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * ip��ַ
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * ��¼ʱ��
	 */
	public void setLogintime(java.lang.String logintime) {
		set("logintime", logintime);
	}
	
	/**
	 * ��¼ʱ��
	 */
	public java.lang.String getLogintime() {
		return getStr("logintime");
	}

	/**
	 * ��¼�豸
	 */
	public void setDevice(java.lang.String device) {
		set("device", device);
	}
	
	/**
	 * ��¼�豸
	 */
	public java.lang.String getDevice() {
		return getStr("device");
	}

	/**
	 * ��¼����
	 */
	public void setLoginos(java.lang.String loginos) {
		set("loginos", loginos);
	}
	
	/**
	 * ��¼����
	 */
	public java.lang.String getLoginos() {
		return getStr("loginos");
	}

}
