package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysRole<M extends BaseSysRole<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * ��ɫ����
	 */
	public void setRolename(java.lang.String rolename) {
		set("rolename", rolename);
	}
	
	/**
	 * ��ɫ����
	 */
	public java.lang.String getRolename() {
		return getStr("rolename");
	}

	/**
	 * ��ɫ˵��
	 */
	public void setRolecomment(java.lang.String rolecomment) {
		set("rolecomment", rolecomment);
	}
	
	/**
	 * ��ɫ˵��
	 */
	public java.lang.String getRolecomment() {
		return getStr("rolecomment");
	}

	/**
	 * �Ƿ����� 0--���� 1--����
	 */
	public void setIsenable(java.lang.String isenable) {
		set("isenable", isenable);
	}
	
	/**
	 * �Ƿ����� 0--���� 1--����
	 */
	public java.lang.String getIsenable() {
		return getStr("isenable");
	}

	/**
	 * ������ID
	 */
	public void setCreateid(java.lang.String createid) {
		set("createid", createid);
	}
	
	/**
	 * ������ID
	 */
	public java.lang.String getCreateid() {
		return getStr("createid");
	}

	/**
	 * ������
	 */
	public void setCreateuser(java.lang.String createuser) {
		set("createuser", createuser);
	}
	
	/**
	 * ������
	 */
	public java.lang.String getCreateuser() {
		return getStr("createuser");
	}

	/**
	 * ����ʱ��
	 */
	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * ����ʱ��
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	/**
	 * �޸���ID
	 */
	public void setUpdateid(java.lang.String updateid) {
		set("updateid", updateid);
	}
	
	/**
	 * �޸���ID
	 */
	public java.lang.String getUpdateid() {
		return getStr("updateid");
	}

	/**
	 * �޸���
	 */
	public void setUpdateuser(java.lang.String updateuser) {
		set("updateuser", updateuser);
	}
	
	/**
	 * �޸���
	 */
	public java.lang.String getUpdateuser() {
		return getStr("updateuser");
	}

	/**
	 * �޸�ʱ��
	 */
	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * �޸�ʱ��
	 */
	public java.lang.String getUpdatetime() {
		return getStr("updatetime");
	}

	/**
	 * (0~5)��,���
	 */
	public void setEnableorglevel(java.lang.String enableorglevel) {
		set("enableorglevel", enableorglevel);
	}
	
	/**
	 * (0~5)��,���
	 */
	public java.lang.String getEnableorglevel() {
		return getStr("enableorglevel");
	}

	/**
	 * ������������
	 */
	public void setEnableorgname(java.lang.String enableorgname) {
		set("enableorgname", enableorgname);
	}
	
	/**
	 * ������������
	 */
	public java.lang.String getEnableorgname() {
		return getStr("enableorgname");
	}

	/**
	 * �ý�ɫ��¼����ҳ��ַ
	 */
	public void setIndexurl(java.lang.String indexurl) {
		set("indexurl", indexurl);
	}
	
	/**
	 * �ý�ɫ��¼����ҳ��ַ
	 */
	public java.lang.String getIndexurl() {
		return getStr("indexurl");
	}

}
