package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysLog<M extends BaseSysLog<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * �û�id
	 */
	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}
	
	/**
	 * �û�id
	 */
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	/**
	 * �û���
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * �û���
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * �û���ʵ����
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	/**
	 * �û���ʵ����
	 */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * ip��ַ
	 */
	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}
	
	/**
	 * ip��ַ
	 */
	public java.lang.String getIp() {
		return getStr("ip");
	}

	/**
	 * ģ��id
	 */
	public void setModuleid(java.lang.String moduleid) {
		set("moduleid", moduleid);
	}
	
	/**
	 * ģ��id
	 */
	public java.lang.String getModuleid() {
		return getStr("moduleid");
	}

	/**
	 * ����ģ��
	 */
	public void setModule(java.lang.String module) {
		set("module", module);
	}
	
	/**
	 * ����ģ��
	 */
	public java.lang.String getModule() {
		return getStr("module");
	}

	/**
	 * �������
	 */
	public void setOperate(java.lang.String operate) {
		set("operate", operate);
	}
	
	/**
	 * �������
	 */
	public java.lang.String getOperate() {
		return getStr("operate");
	}

	/**
	 * ����ʱ��
	 */
	public void setOperateTime(java.lang.String operateTime) {
		set("operate_time", operateTime);
	}
	
	/**
	 * ����ʱ��
	 */
	public java.lang.String getOperateTime() {
		return getStr("operate_time");
	}

}
