package com.baomidou.kisso.dao.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * ID
	 */
	public java.lang.String getId() {
		return getStr("id");
	}

	/**
	 * ��ɫID 
	 */
	public void setRoleid(java.lang.String roleid) {
		set("roleid", roleid);
	}
	
	/**
	 * ��ɫID 
	 */
	public java.lang.String getRoleid() {
		return getStr("roleid");
	}

	/**
	 * ��½�˺�
	 */
	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	/**
	 * ��½�˺�
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * ��ʵ����
	 */
	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}
	
	/**
	 * ��ʵ����
	 */
	public java.lang.String getRealname() {
		return getStr("realname");
	}

	/**
	 * ����
	 */
	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	/**
	 * ����
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * ���֤��
	 */
	public void setIdcard(java.lang.String idcard) {
		set("idcard", idcard);
	}
	
	/**
	 * ���֤��
	 */
	public java.lang.String getIdcard() {
		return getStr("idcard");
	}

	/**
	 * ��ϵ��ʽ
	 */
	public void setTelphone(java.lang.String telphone) {
		set("telphone", telphone);
	}
	
	/**
	 * ��ϵ��ʽ
	 */
	public java.lang.String getTelphone() {
		return getStr("telphone");
	}

	/**
	 * ��ϵ��ַ
	 */
	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	/**
	 * ��ϵ��ַ
	 */
	public java.lang.String getAddress() {
		return getStr("address");
	}

	/**
	 * ��Ƭ·��
	 */
	public void setPhotourl(java.lang.String photourl) {
		set("photourl", photourl);
	}
	
	/**
	 * ��Ƭ·��
	 */
	public java.lang.String getPhotourl() {
		return getStr("photourl");
	}

	/**
	 * �û���ݣ�A�������Ա��N������ͨ�û�
	 */
	public void setUserlevel(java.lang.String userlevel) {
		set("userlevel", userlevel);
	}
	
	/**
	 * �û���ݣ�A�������Ա��N������ͨ�û�
	 */
	public java.lang.String getUserlevel() {
		return getStr("userlevel");
	}

	/**
	 * �����������
	 */
	public void setOrgcode(java.lang.String orgcode) {
		set("orgcode", orgcode);
	}
	
	/**
	 * �����������
	 */
	public java.lang.String getOrgcode() {
		return getStr("orgcode");
	}

	/**
	 * �����������
	 */
	public void setOrgname(java.lang.String orgname) {
		set("orgname", orgname);
	}
	
	/**
	 * �����������
	 */
	public java.lang.String getOrgname() {
		return getStr("orgname");
	}

	/**
	 * �Ƿ����� 0-���� 1-����
	 */
	public void setIsenable(java.lang.String isenable) {
		set("isenable", isenable);
	}
	
	/**
	 * �Ƿ����� 0-���� 1-����
	 */
	public java.lang.String getIsenable() {
		return getStr("isenable");
	}

	/**
	 * �����½ʱ��
	 */
	public void setLasttime(java.lang.String lasttime) {
		set("lasttime", lasttime);
	}
	
	/**
	 * �����½ʱ��
	 */
	public java.lang.String getLasttime() {
		return getStr("lasttime");
	}

	/**
	 * �������
	 */
	public void setOrdernum(java.lang.String ordernum) {
		set("ordernum", ordernum);
	}
	
	/**
	 * �������
	 */
	public java.lang.String getOrdernum() {
		return getStr("ordernum");
	}

	/**
	 * ������
	 */
	public void setCreateuser(java.lang.String createuser) {
		set("createuser", createuser);
	}
	
	/**
	 * ������
	 */
	public java.lang.String getCreateuser() {
		return getStr("createuser");
	}

	/**
	 * ������ID
	 */
	public void setCreateid(java.lang.String createid) {
		set("createid", createid);
	}
	
	/**
	 * ������ID
	 */
	public java.lang.String getCreateid() {
		return getStr("createid");
	}

	/**
	 * ����ʱ��
	 */
	public void setCreatetime(java.lang.String createtime) {
		set("createtime", createtime);
	}
	
	/**
	 * ����ʱ��
	 */
	public java.lang.String getCreatetime() {
		return getStr("createtime");
	}

	/**
	 * �޸���ID
	 */
	public void setUpdateid(java.lang.String updateid) {
		set("updateid", updateid);
	}
	
	/**
	 * �޸���ID
	 */
	public java.lang.String getUpdateid() {
		return getStr("updateid");
	}

	/**
	 * �޸���
	 */
	public void setUpdateuser(java.lang.String updateuser) {
		set("updateuser", updateuser);
	}
	
	/**
	 * �޸���
	 */
	public java.lang.String getUpdateuser() {
		return getStr("updateuser");
	}

	/**
	 * �޸�ʱ��
	 */
	public void setUpdatetime(java.lang.String updatetime) {
		set("updatetime", updatetime);
	}
	
	/**
	 * �޸�ʱ��
	 */
	public java.lang.String getUpdatetime() {
		return getStr("updatetime");
	}

}
